/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fromblender.glb')
  useFrame((state, delta) => (group.current.rotation.y += 0.01))
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.FBHead.geometry} material={materials.FBHead_preview_mat} />
      <mesh geometry={nodes.FBHead001.geometry} material={materials.FBHead_preview_mat} />
    </group>
  )
}

useGLTF.preload('/fromblender.glb')
