/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useCylinder } from "@react-three/cannon"
import { audios } from "../assets/audios.js"


export default function Model({ ...props }) {
    let { punch, kick, gasp, scream } = audios

    const group = useRef()
    const { nodes, materials } = useGLTF("/fromblender.glb")
    const [ref, api] = useCylinder(() => ({ mass: 1}))
    return (
        <group 
            ref={group} 
            {...props} 
            dispose={null} 
            position={[0, 2, 0]}
      
            onClick={() => {
                api.velocity.set((Math.random() - 0.5) * 8, (Math.random()) * 8 , 0)
                api.angularVelocity.set((Math.random() - 0.5) * 10, (Math.random() - 0.5) * 10, (Math.random() - 0.5) * 10)
                const randomNum = Math.floor(Math.random() * 4)
                const randomSound = [punch, kick, gasp, scream][randomNum]
                if (Math.random() > 0.3) randomSound.play()
            }}
        >
            <mesh ref={ref} geometry={nodes.FBHead.geometry} material={materials.FBHead_preview_mat} />
        </group>
    )
}

useGLTF.preload("/fromblender.glb")
